### ISSUE TITLE
ラベル/ボタンの日本語化

### ISSUE THREAD

**Issue by sunmoonStern** [code-for-future-moms/prototype-k#1]
例えば https://www.fukushi.metro.tokyo.lg.jp/kodomo//kosodate/josei/funin/shiteiiryou-jouhoukoukai.files/12_R4_akasakamiyazaki.pdf の【凍結胚を用いた治療成績】をtsvに格納しているので以下のように変更した方がよい。
```
et_count -> 移植総回数（回）
preg_count -> 妊娠数（回）
birth_count -> 生産分娩数（回）
birth_ratio -> 移植あたり生産率（%）
```

**Comment by ktakayama** [comment]
ああ〜、issueがあるの気付いてませんでした
ここ見る前にこうしてしまっていました
c6f699211ad48571c819c80d23e1fdf446af7de5
今こういう感じなので、ラベル名が長いと並べ替えボタンが横長になってしまうかもです

<img width="470" alt="image" src="https://github.com/code-for-future-moms/prototype-k/assets/42468/5bf9f672-c898-4e2d-b581-6fbe306e8d1f">

**Comment by sunmoonStern** [comment]
早速の対応あざます。一応政策秘書さんに進捗共有しようと思っていて、日本語に直さないとサイトをみても意味が通じないかなと思っていたので早速修正いただいてありがたいです。細かいところは公開データの詳細がわかったときに議論するとして当面のところ 🆗 と思います。

**Comment by sunmoonStern** [comment]
対応いただいたのでcloseしときます。
