### ISSUE TITLE
ライセンスを決める

### ISSUE THREAD

**Issue by sunmoonStern** [code-for-future-moms/prototype-k#10]
- 本番公開までにライセンスを決めてLICENSE.txtを書く

**Comment by ktakayama** [comment]
> ユーザアンケート実施するまでにtsvファイルを更新することを考えています。(昔自分が作ったときには医療機関が回答するのが遅くてPDFが公開されていなかったけど、今は公開されている医療機関もあるため。)
> 情報抽出には以前利用したpdfminer.sixではなくよりPDFからテキスト抽出する際にランダム性がないというか、人間がみて同じファイルは同じようにテキストに変換されるPopplerを利用しようかと思っているんですけど、これGPL v2らしいんですよね。

**Comment by ktakayama** [comment]
tsvファイルの更新スクリプトがこのリポジトリに入っていなければ、更新用スクリプトのライセンスとは別にできるかもと思いました

**Comment by sunmoonStern** [comment]
> tsvファイルの更新スクリプトがこのリポジトリに入っていなければ、更新用スクリプトのライセンスとは別にできるかもと思いました

ライセンスについて詳しくなくて、それでいいのか自信ないです。時間できたときに調べてみます。とりあえず情報抽出を本当にPopplerでいくかもまだ本決まりではないので、いったん保留で、情報抽出スクリプトが完成するまではとりあえず待って、本番公開までに決めましょう。本番公開までに決めるのを忘れないようにしたいと備忘録のようにissue作成しましたので

**Comment by sunmoonStern** [comment]
大々的にユーザへアンケートするなら今のサイトはフッターにGitHubへのリンクを貼って簡単にrepositoryにアクセスできるようにあえてしてあるので、repositoryのlicenseを明記しないと信頼されない気がしています。

データとソフトウェアのラインセンスは別々でいい(※出典探したけど見つからず)という考え方に基づくならば、
Takayamaさんも言われているようにMITライセンスでいってみようかなと考えるなどしています。

https://ufal.github.io/public-license-selector/ もdataかsoftwareかでlicense選ぶようになっているし。
