### ISSUE TITLE
K6: 生産率を直感的にわかりやすくする

### ISSUE THREAD

**Issue by sunmoonStern** [code-for-future-moms/prototype-k#102]
- このサイトの存在意義に関わる部分のため慎重に議論したい
- https://github.com/code-for-future-moms/prototype-k/pull/91#issuecomment-1855997252 でいろいろ語ったが、全国平均とほぼ同等、全国平均より高い、全国平均より低い、と離散値で分けると境界をどこにするかが難しいので、やはり棒グラフで全国平均とクリニック成績を比べるしかないかという気持ち

**Comment by sunmoonStern** [comment]
こういうのか
<img width="445" alt="スクリーンショット 2023-12-19 23 37 49" src="https://github.com/code-for-future-moms/prototype-k/assets/15853715/a075d03c-a208-41fe-ab3f-8c3d7613a2ad">
それともこういうのか
<img width="1118" alt="スクリーンショット 2023-12-19 23 38 05" src="https://github.com/code-for-future-moms/prototype-k/assets/15853715/5a19644a-1667-4da0-8704-dae0c012d380">

**Comment by sunmoonStern** [comment]
https://yourivfsuccess.com.au/clinics の方(2枚目のスクショ)を見てて思いましたけど、信頼区間の計算もやらないと 🙄

**Comment by sunmoonStern** [comment]
https://www.jsog.or.jp/activity/art/2021_JSOG-ART.pdf のP33の表8 移植あたり生産率 26.6%との比較として可視化すると良さそう。

**Comment by sunmoonStern** [comment]
@ktakayama yourivfsuccess のグラフって何を使って作られているかわかりますか? 愚直にソースを表示してもちょっとよくわからなくて。

**Comment by ktakayama** [comment]
うーん、なんですかねこれ
ちょっとわかりませんでした 💦

**Comment by sunmoonStern** [comment]
@ktakayama ご確認ありがとうございます。highchartsなど使ったことあるライブラリを使ってやってみます。

HFEAみたいに、全国平均と比べて明らかに高いか、同等か、低いかだけ表示すればいいと思っていたけれど、そもそも移植あたり分娩率は公開しているのに、こども家庭庁のHPのテーブルの情報が正しいとするならば、総採卵数しか公開されていなくて、移植数が公開されていない(＝分母が不明)で信頼区間も計算できないという酷い状況でして。とりあえず各医療機関が公開している移植あたり生産率が正しいと仮定して、参考程度に26.6%と比較するしかないと思っています。本当に、情報公開のあり方を変えたい...

**Comment by sunmoonStern** [comment]
以下いくつかデータを個別に見ていて気づいたことをメモ

杉山産婦人科の 
採卵総回数（回）3944
妊娠数（回）1623
生産分娩数（回）0
の0回とか信じられないわ。何か医療機関側が回答する際に数字を間違って書くとかで、間違ってるんじゃないだろうか。

Shinjuku ART Clinic
や他のいくつかのクリニックで凍結胚の治療成績で
生産分娩数（回）/採卵総回数（回）*100 ~ 移植あたり生産率(%)
という数式が成立しているんだけど、たぶんテーブルの見出しが間違っていて
(誤) 採卵総回数（回）→ (正) 移植総回数(回)
なんじゃないだろうか。そもそも凍結胚で採卵回数の統計ってなんのことか意味わからんし。

**Comment by sunmoonStern** [comment]
@ktakayama 実装の相談なんですけど、検索結果一覧に棒グラフ表示するようにする要素を入れたいときって、`showSearchResult`関数の中で作っているhtmlがありますけど、その中の凍結胚を用いた治療成績が今はtableになっていないですけど、tableに入れて、
https://codepen.io/sunmoonstern/pen/RwdNpEq
みたいに可視化するっていう方向性はありですかね?

**Comment by ktakayama** [comment]
間違ってたらすみません、検索結果の個別の項目に棒グラフを追加するイメージですか？
あまり見ないような表現の気がしておりますが、そうでもないんですかね
検索結果のトップあたりに、グラフとしてまとめるのはありかと思いますが、グラフを見ればいいのか検索結果リストを見ればいいのか、フォーカスがぶれちゃいますね。

**Comment by sunmoonStern** [comment]
@ktakayama なるほどなるほど。
自分は現行の検索結果一覧の凍結胚の治療成績の見せ方に課題を感じていて、k5のように移植あたり出生率をそのままグラフにして見せるだけではいかんな、と思っております。クリニックごとに移植件数が違って、移植件数が多いクリニックほどエラーバーが小さいので。それだけの情報は今検索一覧から読み取れないので。

[births_per_tf.pdf](https://github.com/code-for-future-moms/prototype-k/files/13772375/births_per_tf.pdf)
のグラフを見てほしいんですけど、オレンジ線がだいたい平均だと思って貰えばよくて、エラーバーを考慮してもオレンジ線より出生率低いクリニックにはいくべきでないし、高いクリニックは行くといいと思いますし、この情報を伝えなければ、という思いがあります。

**Comment by ktakayama** [comment]
@sunmoonStern たとえば、検索結果の個別の要素に入れるとなると、こんなイメージですかね？
デザインがいまいちパッとしないんですが…難しい。

<img width="611" alt="image" src="https://github.com/code-for-future-moms/prototype-k/assets/42468/58007e88-8af4-4b8c-825d-83a6f895c551">

なんか同じようなことをやっているサイトなりがあるとわかりやすいんですが。

ちなみに「エラーバー」っていうのは、births_per_tf.pdfの緑色の部分ことですか？

＊年末年始は旅行に行っておるので、あんまりこちらの活動はできないっす 🙏

**Comment by sunmoonStern** [comment]
> ちなみに「エラーバー」っていうのは、births_per_tf.pdfの緑色の部分ことですか？

そうです。より正確には95%信頼区間なのですが。　

同じようなことをやっているサイトについては、
HFEAは検索結果一覧サイトでは → https://www.hfea.gov.uk/choose-a-clinic/clinic-search/results/?location=manchester&distance=25 みたいにエラーバーを考慮して全国平均と同じくらいか高いか低いかあるいはデータ不足かだけを表示している(グラフ表示はしない)から実際にk6の作り方としてはそうすればいいのかなって思ってます。

オーストラリアの方は、個別クリニックのページ
https://yourivfsuccess.com.au/clinics/238?term=&page=0&size=20&locationId=324
に飛んで矢印を押して展開すると、グラフが見られます。
これが元々の自分のイメージには一番近いです。
ただ、以前も話題になった通り、どのように技術的に実現しているのか不明です。
<img width="1141" alt="スクリーンショット 2023-12-29 14 16 33" src="https://github.com/code-for-future-moms/prototype-k/assets/15853715/bfbf3beb-f913-4587-82fa-c3e57f381c05">

＊自分も年末年始自宅から離れていてあまり開発をする時間を取れないので全然大丈夫です。記者さんからも音沙汰ないですし 😅

**Comment by sunmoonStern** [comment]
ずっと作らなければいけない信頼区間つきのグラフを別のエンドポイントに作成 https://github.com/code-for-future-moms/prototype-k/pull/109
なので、k6の方はグラフは不要で、全国平均と比較して信頼区間を考慮すれば同等、よりよい、より悪い、データ不足で信頼区間が大きすぎる、データ非公開
の区別がつけばいいかと思います。

**Comment by sunmoonStern** [comment]
@ktakayama 長らく開発放置していてすみません。
自分としては今最優先で開発したい機能はこのissueで議論しているもので、↑に書いた通り、当面は、生データにカラムを一つ追加して、そこの内容、例えばnot_public,unsufficient_data,better_than_ave,worse_than_aveなどに応じてアイコン表示するのってはどうでしょうか。

**Comment by ktakayama** [comment]
@sunmoonStern アイコンで見せるの良いと思います！

データの内容を役割を教えてもらえれば、アイコン用意します〜。
いまマテリアルアイコンかicons8のアイコンを使っているので、そこから探して必要であれば加工する感じですね。
https://icons8.jp/
https://fonts.google.com/icons

**Comment by ktakayama** [comment]
てか普通に「公表してない・データ不足・平均以上以下」の4つですね

**Comment by ktakayama** [comment]
考えてみたらアイコンも難しいですね。試しにChatGPTに聞いてみたんですけど、指示を工夫しないとぜんぜんだめだ。

<img width="747" alt="image" src="https://github.com/code-for-future-moms/prototype-k/assets/42468/0b6d6cd4-0327-4422-9a40-816a3de4efb4">

**Comment by sunmoonStern** [comment]
アイコン自体はHFEAを参考にしちゃえばよくないですかね? マルパクリはよくないですが、同じ方向性のアイコンをicons8などから発掘すれば。
https://www.hfea.gov.uk/choose-a-clinic/clinic-search/results/?location=london&distance=25
をみると
<img width="193" alt="スクリーンショット 2024-01-25 23 22 08" src="https://github.com/code-for-future-moms/prototype-k/assets/15853715/0d9a9d20-dfc8-4f8a-99fd-476e0ca986c5">
とか
<img width="212" alt="スクリーンショット 2024-01-25 23 22 16" src="https://github.com/code-for-future-moms/prototype-k/assets/15853715/33da97d7-5dcd-4383-8832-09a2eedbb9c8">
とか...

**Comment by ktakayama** [comment]
@sunmoonStern なるほど、テキストを添えるとわかりやすそうですね
治療成績のすぐ下に表示する案を考えて見ましたが、イメージに近いでしょうか？

<img width="576" alt="image" src="https://github.com/code-for-future-moms/prototype-k/assets/42468/f44c4928-c1fa-42ba-a921-c8abd04f0b66">

----

4種類ごとに簡単にアイコンも作ってみたので、それも上の画像に入れています。
HFEAだと、平均以下が [赤いバツマークでなかなか刺激的](https://www.hfea.gov.uk/choose-a-clinic/clinic-search/results/102/) なので、我々のほうではあたりさわりのない表現にしたいなと思って丸だけにしています。
平均以上はチェックマークを採用していますが、他の案としては「二重丸」とか「★」ってのもあるのかなと思っていますがどうでしょうか。
平均以下→丸、平均以上→二重丸っていうのもそんな悪くないのかなーと。

**Comment by sunmoonStern** [comment]
HFEAを参考に5種類にしましょう。
平均以下、以上ではなく、文言は要検討ですが、
全国平均より下、全国平均と同等、全国平均より上
です。スクショの"below, constent with, above"
<img width="389" alt="スクリーンショット 2024-01-29 23 12 11" src="https://github.com/code-for-future-moms/prototype-k/assets/15853715/d260761b-f565-4771-93f0-059e88a0f669">

aboveのアイコンはこれだった
<img width="199" alt="スクリーンショット 2024-01-29 23 21 45" src="https://github.com/code-for-future-moms/prototype-k/assets/15853715/d191684f-240b-4349-981e-25684f74d9dd">

**Comment by ktakayama** [comment]
@sunmoonStern 方針良いと思いますので、データへの反映をお願いしますです〜

**Comment by sunmoonStern** [comment]
@ktakayama ご確認ありがとうございます。ずっと新しいフィールドを追加したデータを作らなきゃ...と思っていましたがなかなか行動に移せなかったのでそう言っていただけると行動に取り掛かれる気がします。今週中には...

**Comment by sunmoonStern** [comment]
以下の点迷っています... 😓 
このまま悩むと何もできなさそうなので、
とりあえずデータ数不足、という判定を足す、というのをあissueにしておいて、
データ数不足、という選択肢は最初はなしでいいのかな...
(以下、悩みポイント)
全国平均より下、全国平均と同等、全国平均より上
や
データが非公開
の判定はすぐできますが、データ不足というのは
参考にしているHFEAのアイコンにはなさそうなのですが、
それでいいんだろうか...!?
あまりに移植数が少なく、95%信頼区間が広すぎて全国平均と同等といっても当てにならないケースとかありますよね。
移植数が例えば30件とか50件未満はデータ不足、とか人為的な基準で足切りしていいんだろうか。
統計的な理論から何件以下はデータ数不足、と導き出せるのだろうか。

**Comment by sunmoonStern** [comment]
解決策思いつきました。フラグは
データ非公開、平均より下、同等、上
の４種類にしましょう。

それで、移植数が
30件未満 → **データ数が極めて少なく、統計的な不確かさが大きい**
30件以上60件未満 → **データ数が少なく、統計的な不確かさがやや大きい**
みたいな注釈を移植数をみて入れることにしましょう。

@ktakayama 大丈夫ですよね? この方針でデータを準備しちゃおうと思っています。

**Comment by ktakayama** [comment]
@sunmoonStern 良いと思います！

**Comment by ktakayama** [comment]
注釈を入れるとしたらこんな感じですかね。

<img width="506" alt="image" src="https://github.com/code-for-future-moms/prototype-k/assets/42468/bdf9ec5a-fb5f-4d96-9faa-b5eb38a7dcf2">

----

各項目ごとのアイコンの案です


<img width="179" alt="image" src="https://github.com/code-for-future-moms/prototype-k/assets/42468/373e6f0c-a709-4d3e-8dcf-db5a5ea3c786">

**Comment by sunmoonStern** [comment]
@ktakayama こちらのデータを使っていただいていいでしょうか?
https://github.com/code-for-future-moms/fetch-open-data/blob/main/data/cfa-20231213v3.tsv

データとしては文字列で
"N/A","worse","consistent","better"
のいずれかが入っています。

**Comment by sunmoonStern** [comment]
@ktakayama ↑のスクショを作るためのブランチあったらpushお願いします。
もうすぐ育休も終わってしまうし、最後の悪あがきとして、この修正だけ入れて、もう一度各メディアに記事やニュースにしてくれるよう情報提供したい。

**Comment by ktakayama** [comment]
@sunmoonStern あ、それ画像なんです
今日時間あるので多分ここの部分は入れられると思いますー

**Comment by sunmoonStern** [comment]
@ktakayama ありがとうございます 🙇🏼‍♀️ 🙇🏼‍♀️ 🙇🏼‍♀️
