### ISSUE TITLE
治療成績を全国平均と比較する際の計算式の開示

### ISSUE THREAD

**Issue by sunmoonStern** [code-for-future-moms/prototype-k#113]
- UI的には※をクリックすると計算式が表示されたり、ベンチマークとして利用している全国平均の移植あたり妊娠率のデータソースへ飛ぶイメージ

**Comment by ktakayama** [comment]
アイコンあたりにマウスを持ってくると表示されるのが、割りと気づきやすくてわかりやすいですかねえ。
<img width="308" alt="image" src="https://github.com/code-for-future-moms/prototype-k/assets/42468/136e9b0d-1f90-4112-b33c-e80db0e11a52">

あとは、こういう感じにしてクリックすると表示したりも案としてはありそう。
<img width="630" alt="image" src="https://github.com/code-for-future-moms/prototype-k/assets/42468/1185a35c-86a1-4dc1-a66d-9191a75023cc">

**Comment by sunmoonStern** [comment]
単純に考えて、1つ目の画像のように、「全国平均より上」という文言の近くに配置するのがいいのではないでしょうか。
例えば、HFEAのiのアイコンは注釈っぽくてよいので、我々のページも注釈っぽさが伝わるアイコンをおけばいいかも
<img width="262" alt="スクリーンショット 2024-02-09 23 04 43" src="https://github.com/code-for-future-moms/prototype-k/assets/15853715/f984c6f0-a38c-401b-b7a8-3bdd81e4e18f">
