### ISSUE TITLE
FAQを作成し、分娩数はどこから取ったという疑問に答える

### ISSUE THREAD

**Issue by sunmoonStern** [code-for-future-moms/prototype-k#115]
すでに2回質問されている

1. https://github.com/code-for-future-moms/create-docs/issues/3
1. https://x.com/rikubo_hatena/status/1758228377599905892?s=20

**Comment by sunmoonStern** [comment]
FAQに掲載すべき内容

Q このページの目的は?
A 体外受精を考えている人向けに医療機関ごとの治療成績をわかりやすく伝えることを目指している。イギリスの[HFEAのFertility clinic search](https://www.hfea.gov.uk/choose-a-clinic/clinic-search/)を参考に有志で制作。

Q 不妊治療専門クリニックなのに分娩数の統計があるのはなぜか?
A 日本産科婦人科学会に流産・死産・出産などの妊娠の経過を報告する義務があるため、各クリニックが追跡調査しているため。

Q 近所の体外受精を実施しているクリニックが掲載されていないけど、なぜ? 
A こども家庭庁医療機関検索からデータを取っているのでここに掲載されていないと原理的に掲載できない。そのクリニックの院長が厚生労働省が取っている統計に回答していないと考えられる。

**Comment by sunmoonStern** [comment]
@ktakayama 他に何か思いつきますかね

**Comment by ktakayama** [comment]
@sunmoonStern 
ページ内の情報と重複しちゃうんですが、治療成績の算出方法と、データソースについても改めてFAQに記載してあってもいいかもしんないです

**Comment by sunmoonStern** [comment]
それ、いい。重要な情報は複数箇所にあっても問題ないですものね。

**Comment by sunmoonStern** [comment]
Q 表示されているデータはどこから取ったの？
A [こども家庭庁医療機関検索](https://funin-fuiku.cfa.go.jp/clinic/)で公開されている数値を利用。

Q 凍結胚の治療成績で「全国平均より高い(低い)」という表示の根拠は?
A (注釈と大体同じ内容を書く)

Q バグを発見した/感想や要望を送りたい
A [メール](code-for-future-moms@ymail.ne.jp)か[X](https://twitter.com/angry_engineer0)までどうぞ
