### ISSUE TITLE
データの更新日時と医療機関の件数をweb UIに表示

### ISSUE THREAD

**Issue by sunmoonStern** [code-for-future-moms/prototype-k#117]
- タイトル通り

**Comment by ktakayama** [comment]
@sunmoonStern 
この内容の表示なんですけど、どう感じにしましょうか
たとえば、何も検索していない初期状態のときに、タイトルの下のスペースに表示するとかあってもいいかもと思いました

<img width="666" alt="image" src="https://github.com/code-for-future-moms/prototype-k/assets/42468/4de913ca-f552-4f54-a528-24013426a2cd">

> こども家庭庁 不妊治療医療機関検索サイトのデータを元に医療機関の検索ができます
> 検索フォームから、検索したい内容を入力してください
> ※当サイトにおけるデータの最終更新日時は2024年4月14日で、現在365件の医療機関が対象です

みたいな
もうちょっと文章をシンプルにできそうなんですけど、すぐ思いつかなくて取り急ぎの案です

**Comment by ktakayama** [comment]
あと、ファイルのデータ（HTTPのヘッダー）から最終更新日時を取るのは無理そうだったので、JSファイル内に定数として定義するのでいいかなと考えています

**Comment by sunmoonStern** [comment]
日時はファイル名をYYYYMMDDの形式で命名してファイル名からパターンマッチで取ればいいんじゃないかと思ってます。issueに書いておけばよかったです。
追記: よく考えると思想としては日付を定数としてJSファイル内に定義して、入力ファイルを探すのと同じかもです。たぶんJSだけで特定のリポジトリにある `cfa-YYYYMMDDv3.tsv` のうち日付が一番遅いもの、とか取るの大変なので

**Comment by sunmoonStern** [comment]
@ktakayama メンションつけ忘れたので

**Comment by sunmoonStern** [comment]
何も検索していないときにタイトル下に表示はぜひやるべきだし、フッターのデータソースのところの横にも "2023/04/14時点のデータを利用"みたいな文言を追加したい
<img width="531" alt="スクリーンショット 2024-04-15 12 32 22" src="https://github.com/code-for-future-moms/prototype-k/assets/15853715/e4d46ddd-e2d3-4b11-9769-b5b6efd39636">
