### ISSUE TITLE
ソートボタンの機能について

### ISSUE THREAD

**Issue by sunmoonStern** [code-for-future-moms/prototype-k#13]
すみません、こちらのボタンって有効に使われていますか?

<img width="299" alt="スクリーンショット 2023-09-07 9 52 56" src="https://github.com/code-for-future-moms/prototype-k/assets/15853715/339f5114-45c5-4a54-8362-0dc8af583f94">

ちゃんとコード追っていないですが、ボタン押してもtableの表示もグラフの表示も意図通りに変わらないような気がします。

**Comment by sunmoonStern** [comment]
ちょっと今週いっぱいは情報抽出スクリプトの実装にかかりそうですが、issueは思いついたものから作成しているだけで、全部実装お願いしますという意図では全然ないです > <

**Comment by sunmoonStern** [comment]
関係するかもしれないですが、このボタン押すと、下のtableのselectされた10個のrowがばらけるのでselectした行が可視化されうるということが伝わりにくい気がします。
また、tableでクリックすると可視化されうる、ということを表すのに、初期状態でtableのrowにselectされているものとされていないもの、両方があった方がいい気がします。https://github.com/code-for-future-moms/prototype-k/issues/2#issue-1879127173 のコメントはそういう意図でした。
例えば、初期表示を7個にしてselectされていないrowを3個残すか、selectされているrowは10個にしたままtableで1ページに表示されるrowを20個くらいに増やすとか、ですかね。

**Comment by ktakayama** [comment]
あー、すみません、ソートボタンは動いてませんでした
3caa9e5d75999a120d0c16a366d03777d2011d00 で修正しました

**Comment by ktakayama** [comment]
> 関係するかもしれないですが、このボタン押すと、下のtableのselectされた10個のrowがばらけるのでselectした行が可視化されうるということが伝わりにくい気がします。
> また、tableでクリックすると可視化されうる、ということを表すのに、初期状態でtableのrowにselectされているものとされていないもの、両方があった方がいい気がします。

そうですね、これは私も触ってて思いましたので、初期ページが全選択された今の状態はよくなさそうで、テーブルの1ページの表示件数をPlotSample*1.5とかにして試したりしていました。

で、#5 と関連していま悩んでいるのは、そもそもテーブルで選択した内容をグラフに表示する必要は無いかも、と考えています。

都道府県は選択できるようにするとして、グラフでは上位XX件を表示して「どんな医療機関があるのか、上位の医療機関のうち自分が通えそうなところはあるのか」を探してもらう。テーブルのほうは数値をじっくりとみながら「自分が通ってる医療機関はどのくらいの成績なのか、気になるあそこはどのくらいなのか」を確認してもらう。という使い方を想定しています。

**Comment by sunmoonStern** [comment]
古いprototypeについてのissueだからcloseしてしまいます。
