### ISSUE TITLE
データが最新でない

### ISSUE THREAD

**Issue by sunmoonStern** [code-for-future-moms/prototype-k#14]
- https://github.com/code-for-future-moms/fetch-open-data/blob/main/data/hospital-data-address-R40620.tsv に最新データをアップしたので、こちらを参照するようにコードを修正したい
- 現時点で東京都のHPに掲載されており、数値に矛盾がない医療機関が全て含まれる
   - これで、やっと自分がお世話になった医療機関も可視化されるようになる 😄

**Comment by ktakayama** [comment]
反映しました〜

**Comment by sunmoonStern** [comment]
どうもありがとうございました 🙇🏼‍♀️ お世話になったところの数字もみられるようになり感無量です。
