### ISSUE TITLE
mainブランチに直接pushできないようにする

### ISSUE THREAD

**Issue by ktakayama** [code-for-future-moms/prototype-k#15]
https://github.com/code-for-future-moms/prototype-k/settings/branch_protection_rules/41271532

いま、ブランチのプロテクションルールでmainブランチを

- Require a pull request before merging

にチェックを入れている状態です。

さきほど操作を誤って、mainブランチに直接pushする操作をしてしまったんですが、通ってしまいました。他に必要あん設定ってありましたっけ…。
なんか確か「アドミンにもこの制限を適用する」みたいなチェックがあった気がしたんですけど、設定画面に見当たらないのでこれは関係ないのかな。なんじゃろう。

**Comment by sunmoonStern** [comment]
自分も知りませんでした。これにチェック入れないといけないってことかな。
![スクリーンショット 2023-09-07 22 38 53](https://github.com/code-for-future-moms/prototype-k/assets/15853715/1fb43c94-4db8-4546-83d7-ff8be1848de2)
他のrepoもチェック入れてなかったら直さないと...

**Comment by ktakayama** [comment]
おおお〜〜〜、これがまさに「アドミンにもこの制限を適用する」みたいなチェックボックスですね！！！チェック入れましたので、大丈夫なはず…
