### ISSUE TITLE
初期状態で選択されている行数変更

### ISSUE THREAD

**Issue by sunmoonStern** [code-for-future-moms/prototype-k#2]
初期状態だとtableの１ページ目の行(10行)が全て選択されている。最初の6行だけ選択するなど、同じページ内に選択された行と選択されていない行がある方がユーザが使い方を理解しやすいかもしれない。
現状は
![スクリーンショット 2023-09-03 23 52 10](https://github.com/code-for-future-moms/prototype-k/assets/15853715/1614e19f-53b5-4930-973c-e628f77897fd)

**Comment by ktakayama** [comment]
たしかにPlotSampleと合わせたほうがいいっすね

**Comment by ktakayama** [comment]
https://github.com/code-for-future-moms/prototype-k/commit/763e032b1094f67ed4fdaae8f80c4d65d2ea9b65
こちらで対応しました

**Comment by ktakayama** [comment]
さわっててちょっと思ったのは、最初は全件表示させて、そこから見たいものに絞り込んで行くほうがわかりやすいかもしんないかもなと考え始めてます
