### ISSUE TITLE
K5: 選択した地域をURLに含めて記憶させる

### ISSUE THREAD

**Issue by ktakayama** [code-for-future-moms/prototype-k#51]
リロードしたりブックマークしたりしても選択した地域は維持したい

**Comment by sunmoonStern** [comment]
これはつまり、実現できれば配偶者などに情報を共有できるということですかね？すっごい良さそう。
自分もこの機能欲しかったんだけど、技術的にできるかどうか自信がなくて。

**Comment by ktakayama** [comment]
はい
特に問題ないです
次にやろうかなと思ってます
