### ISSUE TITLE
K5: エリアの選択肢をデータから取得する

### ISSUE THREAD

**Issue by ktakayama** [code-for-future-moms/prototype-k#53]
現在は固定値になっている
あと、都道府県から選択できるようにしたい

**Comment by sunmoonStern** [comment]
@ktakayama これってファイルを読み込むみたいなのをJSでやる感じでしょうか? その際に、サイトの表示が遅くなるようなことはありますか?

jsは固定値を読み込むとしても、その固定値の生成の掲載されたjsファイルをコンピュータープログラムで機械的に生成するという方向性はありえますか?

**Comment by ktakayama** [comment]
@sunmoonStern 現状読み込んでいるTSVファイルデータの住所欄を使うつもりです。サイトの表示が遅くなるかどうかでいうと、処理を行なう分遅くなるとは思いますけど、すでに色々処理してますし、気になるほど差が出ることはないかと思います。
