### ISSUE TITLE
K6: 問い合わせ先の明示

### ISSUE THREAD

**Issue by sunmoonStern** [code-for-future-moms/prototype-k#88]
- 今後メディアに取り上げらたときのことを考え、問い合わせ先のメールアドレス、Xアカウントの明示が必要

**Comment by ktakayama** [comment]
あ、これもフッターに追加ですね〜

**Comment by ktakayama** [comment]
「開発元」のところですけど「開発に参加する」に変更するのはどうでしょう？

**Comment by sunmoonStern** [comment]
@ktakayama いいと思います！PRになっているけど議論が止まってしまった
https://github.com/code-for-future-moms/prototype-k/pull/86 も進めてREADMEを整備しなければ

**Comment by sunmoonStern** [comment]
メールアドレス → code-for-future-moms@ymail.ne.jp
Xアカウント → https://twitter.com/angry_engineer0
