### ISSUE TITLE
K6: HFEAに習い、検索結果をマップに表示

### ISSUE THREAD

**Issue by sunmoonStern** [code-for-future-moms/prototype-k#92]
- HFEAのサイトはたぶんThe Google Maps JavaScript APIを利用していて課金が発生しているhttps://developers.google.com/maps/documentation/javascript/adding-a-google-map?hl=ja#maps_add_map-javascript
- 課金しなくて済むようにするには https://github.com/code-for-future-moms/prototype-k/pull/79 と同様にするはず

**Comment by sunmoonStern** [comment]
んー、でもAPIでないとフィルターした医療機関だけを地図上に表示とかできないですね。

**Comment by sunmoonStern** [comment]
OpenLayers https://openlayers.org/ がクレカ情報登録しなくても使えて良さそうです。
複数のマーカーを配置した例 https://codepen.io/ronaldaug/pen/dQwNJp

**Comment by ktakayama** [comment]
フィルターの件ですが、そもそも件数がそこまで多くないので治療内容での絞り込みはいらないのではないかなという気がしています。つまり、地図上には全部のクリニックを出してしまい、初期表示を郵便番号で指定した箇所にするっていう風にしても体験としてはそこまで損なわれないかなと感じています。

他の案としては [openstreetmap](https://www.openstreetmap.org/) を使うとかも。

**Comment by sunmoonStern** [comment]
本来は、APIにしてフィルターした結果だけをマップに表示したいので、そのようなことが無料でできるAPIを探そうと思っていたが、マップはどんなものでもいいのではなく、多くのユーザが使い慣れているであろうGoogle Mapであることが大事な気もするので、従来のPR同様マイマップ表示にします。

> 初期表示を郵便番号で指定した箇所にする

これやった方がいいですかね。郵便番号で指定 → マップで表示 か、いきなりマップで表示(マップから医療機関検索する想定)か。

**Comment by sunmoonStern** [comment]
↑のPRはいきなりマップ表示で検索しはじめるという想定

**Comment by sunmoonStern** [comment]
すみません、課金が発生しないように、[API](https://developers.google.com/maps/documentation/embed/get-started?hl=ja#optional_parameters) ではなく[マイマップ](https://www.google.co.jp/intl/ja/maps/about/mymaps/)  機能を使っているのでたぶん入力された郵便番号に対応する緯度経度を中心に開く、とかはそもそもできないと思います。デフォルト設定(常に東京タワーを中心にズームして開く)とかは可能だったとどこかに書いてありました。

**Comment by sunmoonStern** [comment]
https://github.com/code-for-future-moms/prototype-k/issues/108
