### ISSUE TITLE
K6: Google Analyticsの導入

### ISSUE THREAD

**Issue by sunmoonStern** [code-for-future-moms/prototype-k#99]
- K5と同様

**Comment by sunmoonStern** [comment]
https://analytics.google.com/analytics/web/#/p415260372/reports/reportinghub?params=_u..comparisons%3D%5B%7B%22name%22:%22prototype-k6%22,%22isEnabled%22:true,%22filters%22:%5B%7B%22fieldName%22:%22streamId%22,%22expressionList%22:%5B%226472872689%22%5D,%22isCaseSensitive%22:true%7D%5D%7D,%7B%22name%22:%22prototype-k5%22,%22isEnabled%22:true,%22filters%22:%5B%7B%22fieldName%22:%22streamId%22,%22expressionList%22:%5B%226361713762%22%5D,%22isCaseSensitive%22:true%7D%5D%7D%5D%26_u..built_comparisons_enabled%3Dtrue で確認可能

**Comment by ktakayama** [comment]
権限リクエストさせてもらいました！

**Comment by sunmoonStern** [comment]
@ktakayama すみません、権限を付与する必要があるのですね。権限のリクエストをどこでいただいたかわかってないのですが、とりあえずTakayamaさんに閲覧権限つけましたがk5とk6のユーザー数など確認できますでしょうか?

**Comment by ktakayama** [comment]
@sunmoonStern ありがとうございます！！見れました〜〜〜
